language: java
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3

before_install:
  - java -version
  - ./mvnw clean install -DskipTests=true -B -U -V

script:
  - java -version
  - ./mvnw -B -U clean install

cache:
  directories:
    - $HOME/.m2
