language: java
sudo: true
dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3

script:
  - ./mvnw clean verify -B -V

cache:
  directories:
    - $HOME/.m2
